#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 24 18:56:41 2020

@author: usuario
"""

import scipy.stats as st
import math

print("Pregunta 1")  
        



#a)
print("a)")
u=st.uniform(0,1)
n=40
media=n/2
desv=math.sqrt(n/12)
n=st.norm(media,desv)
menora22=n.cdf(22)
print("Según el TCL, n vvaa U(0,1) ")
print("se aproxima a N(n/2, sqrt(n/12))")
print("Por lo tanto para un n igual a "+str(40) +" la probabilidad de")
print("la suma sea menor a 22 es")
print(menora22)


#b)
print("b)")
uni=st.uniform(0,1)
def Sum(uniforme, suma0, muestras, totaldis, frecuenciarelativa1, frecuenciarelativa2):
    for i in range(1,totaldis+1):
        a=uniforme.rvs(muestras)
        suma0=0
        for muestra in a:
            #print(muestra)
            suma0+=muestra
        #print(suma00)
        if (suma0<=22):
            #print("MENOR A 22", "Distribucion "+str(i))
            frecuenciarelativa1+=1
        else:
            frecuenciarelativa2+=1
            #print("MAYOR A 22", i)
            #print("")
    return int(frecuenciarelativa1)
a=(Sum(uni,0, 40, 10000, 0,0))/10000
print("La frecuencia relativa es igual a "+str(a))
    

print("")





#c
print("c)")
print("La probabilidad de que la suma fuera menor a 22 es de "+str(menora22))
print("La frecuencia relativa de sumas menores a 22 para U(0,1) es "+str(a))
print("Las probabilidades son casi idénticas a grandes rasgos")















